apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: clinica
data:
  ADMINISTRATIVO_URL: http://administrativo:8081
  AGENDAMENTO_URL: http://agendamento:8082
  ATENDIMENTO_URL: http://atendimento:8083
  KEYCLOAK_JWK_URI: http://keycloak:8180/realms/clinica/protocol/openid-connect/certs
  KEYCLOAK_ISSUER_URI: http://keycloak:8180/realms/clinica
